apiVersion: v1
kind: Pod
metadata:
  name: spring-hello-pod
  labels:
    app: spring-hello
    tier: backend
spec:
  containers:
  - name: spring-hello
    image: davigomides161/spring-hello:1.0.0
    ports:
    - containerPort: 8080
      name: http
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"