apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring-hello-replicaset
  labels:
    app: spring-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-hello
      tier: backend
  template:
    metadata:
      labels:
        app: spring-hello
        tier: backend
    spec:
      containers:
      - name: spring-hello
        image: davigomides161/spring-hello:1.0.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"